// category
export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';
export const INVALIDATE_CATEGORIES = 'INVALIDATE_CATEGORIES';

// comment
export const REQUEST_COMMENTS = 'REQUEST_COMMENTS';
export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS';
export const REQUEST_ADD_COMMENT = 'REQUEST_ADD_COMMENT ';
export const RECEIVE_ADD_COMMENT = 'RECEIVE_ADD_COMMENT';
export const REQUEST_VOTE_COMMENT = 'REQUEST_VOTE_COMMENT';
export const RECEIVE_VOTE_COMMENT = 'RECEIVE_VOTE_COMMENT';
export const REQUEST_COMMENT = 'REQUEST_COMMENT';
export const RECEIVE_COMMENT = 'RECEIVE_COMMENT';
export const REQUEST_DELETE_COMMENT = 'REQUEST_DELETE_COMMENT';
export const RECEIVE_DELETE_COMMENT = 'RECEIVE_DELETE_COMMENT';
export const REQUEST_EDIT_COMMENT = 'REQUEST_EDIT_COMMENT';
export const RECEIVE_EDIT_COMMENT = 'RECEIVE_EDIT_COMMENT';

// post
export const REQUEST_POSTS = 'REQUEST_POSTS';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export const REQUEST_ADD_POST = 'REQUEST_ADD_POST';
export const RECEIVE_ADD_POST = 'RECEIVE_ADD_POST';
export const INVALIDATE_CATEGORY = 'INVALIDATE_CATEGORY';
export const REQUEST_VOTE = 'REQUEST_VOTE';
export const RECEIVE_VOTE = 'RECEIVE_VOTE';
export const REQUEST_POST = 'REQUEST_POST';
export const RECEIVE_POST = 'RECEIVE_POST';
export const REQUEST_DELETE_POST = 'REQUEST_DELETE_POST';
export const RECEIVE_DELETE_POST = 'RECEIVE_DELETE_POST';
export const REQUEST_EDIT_POST = 'REQUEST_EDIT_POST';
export const RECEIVE_EDIT_POST = 'RECEIVE_EDIT_POST';

// select
export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const SELECT_SORT = 'SELECT_SORT';
